bucket_name: frontend.${EnvironmentName}.${DnsDomain}
cloudfront_component_name: cloudfront

origins:
  s3bucket:
    source: s3


# bucket_policy:
#   OpsAccount:
#     principal:
#       AWS: arn:aws:iam::123456789:root
# components:
#   cloudfront:   # This must match 'cloudfront_component_name'
#     config:
#       comment: Frontend in S3
